### ISSUE TITLE
Mouse cursor moved on external display

### ISSUE THREAD

**Issue by michalsliwa** [inket/Autoclick#1]
When i activate Autoclick when mouse cursor is on external screen (DELL U3818DW, resolution 3840 × 1600), cursor moves with every click downwards around 1/4 length of the screen, eventually reaching bottom and staying there. Does not happen on internal display. In display settings, resolution is scaled with "more space" to achieve native resolution (for some reason selecting default resolution causes it to switch to 1920x800) - maybe it messes with how you calculate cursor position? Macbook Pro 16" 2019

**Comment by inket** [comment]
Thanks for reporting this. Will look into it.

**Comment by michalsliwa** [comment]
Tested with 2.0.1 (4), issue still persist in my setup

**Comment by inket** [comment]
Can you take a screenshot of your Displays > Arrangement like this?

![display-arrangement-macos](https://user-images.githubusercontent.com/679224/107304960-61fcef80-6ac5-11eb-9b6b-75435a3e3962.jpg)

**Comment by michalsliwa** [comment]
![Screenshot 2021-02-09 at 09 24 33](https://user-images.githubusercontent.com/7147201/107336221-23f9ce80-6ab9-11eb-8bbc-161893703598.png)
Thats my regular setup, when i change to something similar like your's screenshot, problem does not appear anymore:
![Screenshot 2021-02-09 at 09 27 07](https://user-images.githubusercontent.com/7147201/107336331-3ffd7000-6ab9-11eb-998c-6e5b3a77e5b8.png)

**Comment by inket** [comment]
Thank you for adding the details! This should be fixed in the newest version once this issue is closed. Please confirm if it solves the issue!

**Comment by c0ldplasma** [comment]
Can confirm its solved. Thanks! :)
