### ISSUE TITLE
Allow set multiple click positions

### ISSUE THREAD

**Issue by cmsax** [inket/Autoclick#10]
Thanks for the nice tool! It would be very convenient when there are multiple objects on screen need to be clicked if `Autoclick` supports set click positions and click them sequentially!

In that way, `Autoclick` may consider following issues:
- multi screen support
- multi position
- sequential click
- shortcut to tag a position on screen

**Comment by inket** [comment]
Thanks for the suggestion! Sadly, that's not the aim for this app; you will need to look for an alternative app or [use Automator](https://apple.stackexchange.com/a/429230).

**Comment by cmsax** [comment]
Thanks!
