### ISSUE TITLE
Higher click rate

### ISSUE THREAD

**Issue by AyAyRON123** [inket/Autoclick#11]
I downloaded the auto clicker from the website and was wondering how I can get more than 50 cps? 

Regards, Aaron

**Comment by inket** [comment]
Please download the unlocked version from here: https://tars.mahdi.jp/apps/autoclick-unlocked.zip

**Comment by AyAyRON123** [comment]
Thank You!

**Comment by AyAyRON123** [comment]
do you have a specific website where you check if it can actually click that fast. when I try its not even getting close to 10000 cps?

**Comment by inket** [comment]
It seems the system doesn't allow more than 1000 clicks per second.

Actually, whichever app is being clicked on will hang until it can process all the clicks, at the rate of 1000cps. For example if you set Autoclick to 10000, then click on an app for a second, the target app will hang for 10 seconds.

I can't do anything about this :/

**Comment by RUGAY** [comment]
then make a limit for 994 so ppl don't get confused
