### ISSUE TITLE
The max value for click rate is still 50 per second.

### ISSUE THREAD

**Issue by NepPure** [inket/Autoclick#15]
Hi, I see  ae110f556022af4f53a8286c89e02b8e88e0f575
but the max value for click rate is still 50 per second.

Download form Readme.

![image](https://user-images.githubusercontent.com/12379907/147479872-e05c3046-6e26-4ce7-96d2-1419b1cf4829.png)

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/147480094-79d9534a-9aa4-47e8-ac13-de43a4e579b4.png)

M1 MAX

**Comment by NepPure** [comment]
There is no problem when I compile from source code, maybe the download link is not updated.

**Comment by inket** [comment]
The download link was not updated on purpose as the higher click rate was not tested: https://github.com/inket/Autoclick/issues/11#issuecomment-966278802

As expected, it caused problems once above a certain number and people still found that link and bugged me about it https://github.com/inket/Autoclick/issues/11#issuecomment-998326311

I don't intend to make the unlocked version the official release as I can't be bothered with people's requests and grievances when it doesn't work well for them.
