### ISSUE TITLE
"Tab"hot key not working. 

### ISSUE THREAD

**Issue by 8483723823** [inket/Autoclick#2]
Fk

**Comment by inket** [comment]
Autoclick uses the library [Kentzo/ShortcutRecorder](https://github.com/Kentzo/ShortcutRecorder) for recording shortcuts.

ShortcutRecorder does not allow using the `fn` key as a modifier (so [fn+anything is not possible](https://github.com/Kentzo/ShortcutRecorder/issues/132)).

However I can enable hotkeys without modifiers, and as such using 'Tab' alone should be possible.

This issue will be closed automatically when a new version of Autoclick is released. That version should support 'Tab' as a hot key.
