### ISSUE TITLE
Allow to use mouse buttons as start / stop hotkey

### ISSUE THREAD

**Issue by nilsreichardt** [inket/Autoclick#5]
## Description
I want to use Mouse 3 (mouse middle click) or other mouse buttons to start / stop. But it doesn't work. Would be nice to be able to do this.

![image](https://user-images.githubusercontent.com/24459435/113563956-d9a05400-9608-11eb-9950-f797f9f52f55.png)

**Comment by nilsreichardt** [comment]
I think this is blocked by https://github.com/Kentzo/ShortcutRecorder/issues/136

**Comment by inket** [comment]
Indeed it is! Maybe you can use BetterTouchTool to map the mouse button to a hotkey that you choose in Autoclick?
