### ISSUE TITLE
Prompt to add AutoClick to Input Monitoring

### ISSUE THREAD

**Issue by PrimaryPixel** [inket/Autoclick#7]
I'm a first time user of AutoClick program. I naively clicked 'Start' button believing that clicking the **fn** key would stop the autoclicking. 
I was wrong. 
Since the AutoClick program did not ask for the Input Monitoring permissions, I did not give the permissions needed. It would helpful for new users if the program prompted to give AutoClick program Input Monitoring permissions. 
Thank you and have a great rest of your day.

**Comment by inket** [comment]
Good catch! Thank you for telling me

**Comment by inket** [comment]
Hopefully fixed with https://github.com/inket/Autoclick/commit/2178d427f0272e9e8e6126193d2a91643b6c1fc5 and https://github.com/inket/Autoclick/commit/a93d83de622f888e7397eca6a641b4dc1f8a10d4. Thanks for reporting it!
